package mushroommantoad.mmpmod.gui.client.tome.pages;

import net.minecraftforge.api.distmarker.Dist;
import net.minecraftforge.api.distmarker.OnlyIn;

@OnlyIn(Dist.CLIENT)
public class PagesDisplayText 
{
	//
	// VIMION
	//
	
	public static String HOVER_VIMIONIC_TOME = "Click me for an introduction to navigating the Vimionic Tome";
	public static String GREY_VIMIONIC_TOME = "Well, something broke. You shouldn't be able to see this text. Please report whatever you just did on the issue tracker on Curseforge!";
	public static String GOLD_VIMIONIC_TOME = "The Vimionic Tome can be used to view information about and progress towards various aspects of the Vimion Mod.";
	
	public static String HOVER_VIMION_GEMSTONE = "Craft a Vimion Gemstone from four Vimionite Shards";
	public static String GREY_VIMION_GEMSTONE = "The same shards that were used to craft this Tome seem to want to bind together in groups of four. Using the Crafting Table, it should be possible to assemble a Gemstone from this new, dephased material by placing it in a 2x2 square. In fact, the shards combine so readily, even inventory crafting should work for this.";
	public static String GOLD_VIMION_GEMSTONE = "Vimion: a material that emits a strong, unidentified energy when life forms are near it. This energy seems to scale with the size of the life form near it, so its reaction to, for example, a Chicken is far less than its reaction to, say, a Cow. Analysis of this material at the atomic level has revealed that there are, in fact, no atoms involved whatsoever. If this observation is correct, Vimion is the first known material made entirely of Magic in a stable structure." + "\n\n" + "This property seems to be consistent with how malleable Vimion is. While it is most stable in a crystalline gemstone structure, it will readily deform and bind to other substances. This property makes its potential as a tool material by itself small, but the possibility of combining it with other tools to create objects with heightened magical properties is greater than any other known substance!" + "\n\n" + "Research into this substance is certain to yield fascinating results!";
	
	public static String HOVER_ADVANCED_GEOLOGIC_PHASER = "Surround a Geologic Phaser with Vimion Gemstones in the Crafting Table to craft an Advanced Geologic Phaser";
	public static String GREY_ADVANCED_GEOLOGIC_PHASER = "One of our first ideas for a use of Vimion was to surround a Geologic Phaser with the gemstones in a Crafting Table. This \"Advanced\" Geologic Phaser should be able to dephase at a different frequency, potentially leading to new discoveries!";
	public static String GOLD_ADVANCED_GEOLOGIC_PHASER = "This new tool has proven to be extremely powerful. First, the Vimion seemed to strengthen the Phaser, granting it much more durability. However, even more importantly, this \"Advanced\" Geologic Phaser has been reported to be able to dephase at least four new ores. As such, new objectives have been added to this Tome for each of these. It's time to head back down to the caves to try to locate these new materials with the Advanced Geologic Phaser, and to try to discover their properties and uses!";
	
	public static String HOVER_SPIRITS_QUESTION = "Craft a Vimionite Dagger to harvest the Spirits of certain Mobs";
	public static String GREY_SPIRITS_QUESTION = "While Vimion is a brittle material, one Miner figured out a way to form it into a fairly strong dagger. This can now be done on any standard crafting table by using Vimion Gemstones and a Stick in the same way you would craft a Diamond Sword from Diamonds and a Stick. A dagger that kills things while it emits a strong life-based energy should have some interesting effect, right?";
	public static String GOLD_SPIRITS_QUESTION = "It took almost a week for anyone to find something truly remarkable about this new tool, and interestingly, it was the wife of a farmer that lost his mind and slaughtered all of his livestock with his Vimionite Dagger. In the aftermath of the destruction, his wife noticed that among the raw beef, pork, chicken, mutton, and rabbit, there were small, glowing, green objects." + "\n\n" + "These were eventually confirmed to be chunks of the Vimion Dagger that had broken off at the time of the animals' death and bound to their souls, trapping them in our universe. This has potentially massive implications, both for Miners and philosophers!" + "\n\n" + "More research must be done into this supernatural phenomenon!";
	
	public static String HOVER_OBTAIN_MOB_SPIRIT = "Kill a farm animal with the Vimionic Dagger to try to obtain a Mob Spirit";
	public static String GREY_OBTAIN_MOB_SPIRIT = "So far, tests have only shown the Vimionite Dagger to be capable of harvesting the spirits of Chickens, Cows, Pigs, Rabbits, and Sheep. However, this harvesting is not guaranteed, and multiple animals of a species may have to be killed with the Vimionite Dagger before a spirit is obtained.";
	public static String GOLD_OBTAIN_MOB_SPIRIT = "These Mob Spirits are fascinating objects! It seems that at the exact moment an animal's spirit separates from its body, there’s a small chance that a piece of the fragile Vimionite Dagger will break off and bind to it. From then on, the spirit treats the Vimionite fragment as if it were its body." + "\n\n" + "This opens up several questions about both the structure and nature of life, but I’ll leave those to the philosophers. For now, I, like most of the team, just want to know what these Spirits can be used for!";
	
	//
	// NECRION
	//
	
	public static String HOVER_NECRION_GEMSTONE = "Craft a Necrion Gemstone from four Necrionite Shards";
	public static String GREY_NECRION_GEMSTONE = "Necrion seems to be far less common than Vimion, although they both seem to appear at around the same depths. While the ore has no reaction at all to the regular Geologic Phaser, it can easily be dephased by a single use of the Advanced Geologic Phaser. The ore reportedly drops shards, which can be used to create a Necrion Gemstone in the same way as Vimion.";
	public static String GOLD_NECRION_GEMSTONE = "Necrion has earned its name from its association with death. It seems to behave exactly opposite to Vimion in that it emits its strongest energy near death or the undead." + "\n\n" + "More information will be added here as it becomes available.";
	
	public static String HOVER_NECRION_SUMMONER = "Craft a Necrionite Summoner to reincarnate Mob Spirits!";
	public static String GREY_NECRION_SUMMONER = "The Necrionite Summoner, a device first created by a Miner living in an End Pillar, may be the key to unlocking the potential of Mob Spirits. By laying a table of three Necrion Gemstones on top of a base of three Obsidian Blocks, a device that bridges the gap between whatever “spirit world” apparently exists and reality can be crafted. Placing this device and using a Mob Spirit on it will summon a ghostlike version of that entity. Very little is currently understood about this process.";
	public static String GOLD_NECRION_SUMMONER = "The reincarnated mob Spirits have been called Spectral Entities, and they, as expected, have many interesting properties. Besides making deep, resonant sounds as they move around, these animals are also popular – with the undead. Upon their arrival from \"beyond,\" nearly every undead mob in the area is instantly drawn to their location with intent to kill. It seems as though these undead monsters are trying to steal this exposed soul for themselves. We should probably prevent them from doing this..." + "\n\n" + "Another interesting property of these mobs is that they've never lost their love of food. These Spectral Entities can still be led in the same way their respective physical counterparts can (ex. the Spectral Sheep will follow a player holding wheat). They will also willingly eat these foods, although this will not trigger a breeding response. Instead, eating causes the Spectral Entities to emit a pulse of Vimionic energy that rekindles the aggression of nearby undead mobs towards them. These properties are certain to have plenty of uses, and more properties will likely be discovered in the future." + "\n\n" + "The question also still stands why these five mobs are the only ones that can yield their souls to a Vimionite Dagger. There must be a way to obtain the souls of other, slightly more complex creatures through similar means at the very least, right?";
	
	//
	// SOLARION
	//
	
	public static String HOVER_SOLARION_GEMSTONE = "Craft a Solarion Gemstone from four Solarionite Shards";
	public static String GREY_SOLARION_GEMSTONE = "Solarion seems to be far less common than Vimion, although they both seem to appear at around the same depths. While the ore has no reaction whatsoever to the regular Geologic Phaser, it can easily be dephased by a single use of the Advanced Geologic Phaser. The ore reportedly drops shards, which can be used to create a Solarion Gemstone in the same way as Vimion.";
	public static String GOLD_SOLARION_GEMSTONE = "Solarion is a fascinating new material in that it seems to absorb energy from the Sun that it can then emit when in dark places. It's association with the Sun has given this material its name." + "\n\n" + "More information will be added here as it becomes available.";
	
	public static String HOVER_SOLARIONITE_PICKAXE = "Craft a Solarionite Pickaxe";
	public static String GREY_SOLARIONITE_PICKAXE = "It seems to be possible to craft a pickaxe imbued with the powers of the Sun using Solarion Gemstones and sticks in the same way you would make a standard pickaxe. Many people have reported that this pickaxe can be used to make locating ores, especially phased ones (such as Vimionite Ore), much easier. It's definitely worth crafting one for ourselves to see what it can do.";
	public static String GOLD_SOLARIONITE_PICKAXE = "This pickaxe isn't so much \"imbued with the powers of the Sun\" as it is capable of capturing and using them. While it has just one functionality, it has several fairly-complex steps involved in using it effectively." + "\n\n" + "First, the Solarionite Pickaxe has to be \"charged;\" upon crafting it, it will have 0 Charge. To charge it, you have to stand in direct sunlight with the pickaxe anywhere in your inventory. This will increase the Pickaxe's Charge at a rate of twenty per second up to 2500 Charge." + "\n\n" + "Once the Solarionite Pickaxe has some charge, it can be right-clicked to activate it. In this state, it will stop charging and begin using twenty Charge per second while it searches for nearby ores. This search has a maximum range directly proportional the Pickaxe's charge, with its maximum range being 8 blocks away at 1600 charge or more." + "\n\n" + "If it finds an ore or other rare block within this radius, it will send out a small flame trail leading to the ore. This will even work on phased ores, making them much easier to locate. If multiple ore blocks are found within the range, the flame trail will point to the closest ones to your feet. This will work whether you're holding the Solarionite Pickaxe or just have it somewhere in your inventory." + "\n\n" + "Rick-clicking the pickaxe again will change it back to its original state of charging when exposed sunlight and doing nothing else special. The pickaxe will also be returned to its original state if it runs out of charge." + "\n\n" + "Mining level appears identical to that of an Iron Pickaxe.";
	//
	// NIHILION
	//
	
	public static String HOVER_NIHILION_GEMSTONE = "Craft a Nihilion Gemstone from four Nihilionite Shards";
	public static String GREY_NIHILION_GEMSTONE = "Nihilion seems to be far less common than Vimion, although they both seem to appear at around the same depths. While the ore has no reaction whatsoever to the regular Geologic Phaser, it can easily be dephased by a single use of the Advanced Geologic Phaser. The ore reportedly drops shards, which can be used to create a Nihilion Gemstone in the same way as Vimion.";
	public static String GOLD_NIHILION_GEMSTONE = "WARNING: Nihilion is an extremely volatile and dangerous material. Several Miners have reported phenomenon ranging from items disappearing from chests containing Nihilion to whole buildings disappearing around it. This gemstone's ability to annihilate materials has given it its name: Nihilion." + "\n\n" + "More information will be added here as it becomes available.";
	
	public static String HOVER_NIHILIONITE_AXE = "Craft a Nihilionite Axe";
	public static String GREY_NIHILIONITE_AXE = "While Nihilion is an extremely volatile substance in its raw form, this destructive tendency can likely be focused into a useful tool. One Miner designed the original Nihilionite Axe to attempt to do just that. Through arranging Nihilionite Gemstones and Sticks in the Crafting Table in the same pattern used to make a regular axe, the Nihilionite Axe can be obtained. Exactly what this tool is capable of remains to be seen.";
	public static String GOLD_NIHILIONITE_AXE = "The Nihilionite Axe delivers on its promise to focus the destructive potential of Nihilion! In its normal state, this Axe functions just like any other axe, although it seems to already be very efficient." + "\n\n" + "Once the Axe is right-clicked, its real potential begins to show. In its active state, the Nihilionite Axe will mine all blocks adjacent to any block mined that are the same as the original block. For example, if it's used on the base of a Birch Tree, every Birch Log will be broken by the axe." + "\n\n" + "This functionality has a few limitations. The largest of these is that it does not work diagonally - it will only break blocks that another broken block shares a face with. This axe can also only be used with blocks that can normally be mined with a hand. This means it will also work with blocks that wouldn't necessarily be mined with an axe, such as sand, dirt, grass, and so on. A third limitation is that while the axe will look for adjacent blocks almost infinitely vertically, it can only check blocks up to 16 blocks away on the X and Z axes." + "\n\n" + "Despite these three key limitations, the Nihilionite Axe seems to be an extremely powerful tool that should prove very effective at speeding up resource collection!";
	
	//
	// EXPION
	//
	
	public static String HOVER_EXPION_GEMSTONE = "Craft a Expion Gemstone from four Expionite Shards";
	public static String GREY_EXPION_GEMSTONE = "Expion seems to be far less common than Vimion, although they both seem to appear at around the same depths. While the ore has no reaction whatsoever to the regular Geologic Phaser, it can easily be dephased by a single use of the Advanced Geologic Phaser. The ore reportedly drops shards, which can be used to create a Expion Gemstone in the same way as Vimion.";
	public static String GOLD_EXPION_GEMSTONE = "Staring deep into an Expion Gemstone, it's possible to see what appears to be an entire universe contained within the stone. This deep, beautiful expanse gave this stone its name: Expion" + "\n\n" + "More information will be added here as it becomes available.";
	
	public static String HOVER_EXPIONITE_SPADE = "Craft an Expionite Spade";
	public static String GREY_EXPIONITE_SPADE = "Mount a pocket dimension on the end of a couple of sticks like a shovel... sure, why not? Allegedly, rounding out the shape produces a sort of shovel that can mine more effectively than any other tool ever created. We should give this a try to see if the so-called \"Expionite Spade\" is useful, and to see if it gives us any additional insight into what Expion may be capable of.";
	public static String GOLD_EXPIONITE_SPADE = "I couldn't have hoped for more interesting results from this tool! While it isn't very efficient - a wooden shovel is substantially faster - and it is extremely fragile - it can only harvest about 250 blocks (without Unbreaking) before shattering - it's properties are incomparable to any other item I've ever seen!" + "\n\n" + "One of the first things we noticed is that enchanting the Expionite Spade doesn't give it that signature purple aura. Instead, that glow seems reserved for activating the tool via right-click. In this state, this Spade's real potential becomes apparent." + "\n\n" + "Whenever it is used to mine a block that can normally be harvested with the hand and is most effectively mined with a shovel, it will consume 64 of the Spade's durability and drop 64 copies of that block! This is an intensely powerful functionality, and I fear it may have dangerous consequences if used improperly." + "\n\n" + "Early tests show that the Expionite spade emits almost exactly 6.3 MJ of a new form of energy when it harvests a valid block while in active mode. This number is consistent with some predictions that the Spade creates and destroys pocket dimensions one cubic meter in size over and over until it has created a stack of items. If this is the case, then it would seem we've discovered a tool that could allow us to make our own dimensions if wielded properly! This has huge implications indeed! More research into the properties of Expion is certainly needed!" + "\n\n" + "And to think, this all started with a shovel...";
}
